### ISSUE TITLE
515 beta panic - scheduler context missing

### ISSUE THREAD

**Issue by covertcorvid** [Putnam3145/auxmos#69]
Occurred on NSV13 (Beestation downstream) with byond 515.1604
DLL compiled with trit_fire_hook, plasma_fire_hook, generic_fire_hook, and fastmos.

```
thread '<unnamed>' panicked at 'scheduler context missing', C:\Users\runneradmin\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-0.2.25\src\runtime\basic_scheduler.rs:294:31
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread '<unnamed>' panicked at 'assertion failed: c.get().is_entered()', C:\Users\runneradmin\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-0.2.25\src\runtime\enter.rs:221:13
stack backtrace:
   0: 0x712a59a8 - bz_internal_error
thread panicked while panicking. aborting.
```

**Comment by jupyterkat** [comment]
This is a rust-g panic, not auxmos. Did you do something with it instead? Deleted the code to set up rust-g's scheduler?

**Comment by covertcorvid** [comment]
Weh, it is. I don't know what went wrong here but not your problem I guess.
